'use client'
// import type { Metadata } from "next";
// import { Roboto_Mono, Ubuntu_Mono } from "next/font/google";
import { Ruda } from "next/font/google";

import "./globals.css";
// import bootstrap style
import 'bootstrap/dist/css/bootstrap.css'
import {useEffect} from "react";



// const inter = Inter({ subsets: ["latin"] });

const MontserratSans = Ruda({
  subsets: ['cyrillic'],
  display: "swap",
  variable: '--font-roboto-mono'
});

// const UbuntuMono = Ubuntu_Mono({
//   weight: "400",
//   subsets: ['cyrillic'],
//   display: "swap",
//   variable: '--font-ubuntu-mono'
//   })
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
{
  useEffect(() => {
    if (typeof window !== "undefined") {
      require('bootstrap/dist/js/bootstrap.js')
    }
  }, [])
  return (
      <html lang="ru" data-bs-theme="light">
      <body className={`${MontserratSans.className} font-sans`}>{children}</body>
      {/*<body className={RobotoMono.className}>{children}</body>*/}


      </html>
  );
}
